# @uri = http://127.0.0.1:8081/
@uri = https://118.178.196.114:8081/
###
POST {{uri}}add
# Content-Type: application/json

{
  "tiXing": "danxuan",
  "tiKu": "gaoshu"
}

###
GET {{uri}}getQuestion?tiku=政治&zhuti=中国近代史纲要&zhangjie=第一章：反对外国侵略的斗争
###
POST {{uri}}add
 Content-Type: application/json

{
  "tiku": "zhengzhi",
  "zhangjie": "导论",
  "zhuti": "毛中特"
}
###

POST {{uri}}addUserInfo
 Content-Type: application/json

{
  "nickName": "S1mple",
	"avatarUrl": "123",
	"openId": "abcdefg"
}

###

POST {{uri}}addCuoti
 Content-Type: application/json

{
	"openId": "oRmia5SdklxEao6BVsTc0kkKRV0k",
  "cuotiList": ["888","456"]
}
###
POST {{uri}}addZhangjie
 Content-Type: application/json

{
	"tiku": "政治",
  "zhuti": "中国近代史纲要",
  "zhangjie": "第一章：反对外国侵略的斗争",
  "subzhuti": "史纲"
}
###
POST {{uri}}getCuotiList
 Content-Type: application/json

{
  "cuotiList": ["5e89fba64997952b64f09520", "5e89fbe74997952b64f09521"]
}